### ISSUE TITLE
Validate request payload

### ISSUE THREAD

**Issue by hamxabaig** [thinblock/key-secret-microservice#4]
https://github.com/thinblock/key-secret-microservice/blob/f9b98915c3d83f7190187ca4fe2601eb4b0e69ff/app/modules/pair/pair.controller.ts#L18-L22

We should validate the request payload, I just posted it without the `user_id` and it saved `undefined` in `user_id` place 😆

**Comment by abdullahtariq91** [comment]
I'll check it out!
